migrate_source: "file://database/migration"

# it is for db localhost 
db_source: "postgresql://postgres:postgres@localhost:5432/notif_db?sslmode=disable"

# it is for cache localhost
redis_source: "redis://:@localhost:6379/0"
cache_ttl: 1m

# http server localhost
http_server:
  address: "localhost:8080"
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 30s
  max_header_bytes: 1048576
